/**
 * Renders a ```mermaid fence as an SVG.
 * The mermaid library is split from the main bundle via dynamic import.
 * Render errors are shown as an error box without crashing the app.
 */
import { useEffect, useRef, useState } from 'react';

let mermaidReady: Promise<typeof import('mermaid').default> | null = null;

function loadMermaid(): Promise<typeof import('mermaid').default> {
  if (!mermaidReady) {
    mermaidReady = import('mermaid').then((mod) => {
      const mermaid = mod.default;
      mermaid.initialize({ startOnLoad: false, securityLevel: 'strict' });
      return mermaid;
    });
  }
  return mermaidReady;
}

let idSeq = 0;

export function MermaidDiagram({ code }: { code: string }) {
  const [svg, setSvg] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  // Stable identifier used to avoid re-rendering the same code (fixed per render)
  const idRef = useRef<string>(`mmd-${(idSeq += 1)}`);

  useEffect(() => {
    let cancelled = false;
    setError(null);
    loadMermaid()
      .then((mermaid) => mermaid.render(idRef.current, code))
      .then(({ svg }) => {
        if (!cancelled) setSvg(svg);
      })
      .catch((err: unknown) => {
        if (!cancelled) {
          setError(err instanceof Error ? err.message : String(err));
        }
      });
    return () => {
      cancelled = true;
    };
  }, [code]);

  if (error) {
    return (
      <div className="sb-mermaid-error" role="alert">
        <div className="sb-mermaid-error__title">Mermaid render error</div>
        <pre>{error}</pre>
      </div>
    );
  }
  if (svg === null) {
    return <div className="sb-mermaid sb-mermaid--loading">Rendering diagram…</div>;
  }
  return (
    <div
      className="sb-mermaid"
      // Embed the SVG generated by mermaid
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}
