/**
 * Renders a ```mermaid fence as an SVG.
 * The mermaid library is split from the main bundle via dynamic import.
 * Render errors are shown as an error box without crashing the app.
 */
import { useEffect, useRef, useState } from 'react';

let mermaidReady: Promise<typeof import('mermaid').default> | null = null;

function loadMermaid(): Promise<typeof import('mermaid').default> {
  if (!mermaidReady) {
    mermaidReady = import('mermaid').then((mod) => {
      const mermaid = mod.default;
      mermaid.initialize({ startOnLoad: false, securityLevel: 'strict' });
      return mermaid;
    });
  }
  return mermaidReady;
}

let idSeq = 0;

export function MermaidDiagram({ code }: { code: string }) {
  const [svg, setSvg] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  // Stable identifier used to avoid re-rendering the same code (fixed per render)
  const idRef = useRef<string>(`mmd-${(idSeq += 1)}`);

  useEffect(() => {
    let cancelled = false;
    setError(null);
    loadMermaid()
      .then((mermaid) => mermaid.render(idRef.current, code))
      .then(({ svg }) => {
        if (!cancelled) setSvg(svg);
      })
      .catch((err: unknown) => {
        if (!cancelled) {
          setError(err instanceof Error ? err.message : String(err));
        }
      });
    return () => {
      cancelled = true;
    };
  }, [code]);

  if (error) {
    return (
      <div
        className="my-[1.2em] rounded-lg border border-[#fecaca] bg-[#fef2f2] px-3.5 py-3"
        role="alert"
      >
        <div className="mb-1.5 font-semibold text-[#b91c1c]">Mermaid render error</div>
        <pre className="m-0 bg-transparent p-0 text-[12px] text-[#7f1d1d]">{error}</pre>
      </div>
    );
  }
  if (svg === null) {
    return (
      <div className="my-[1.2em] flex justify-start overflow-x-auto rounded-lg border border-border bg-background px-4 py-4 text-[13px] text-muted-foreground">
        Rendering diagram…
      </div>
    );
  }
  return (
    <div
      className="my-[1.2em] flex justify-center overflow-x-auto rounded-lg border border-border bg-background px-4 py-4 [&_svg]:h-auto [&_svg]:max-w-full"
      // Embed the SVG generated by mermaid
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}
